version: '2'
services:
  hockeypuck:
    build:
      context: ../../..
    ports:
    - "11370:11370"
    - "11371:11371"
    restart: always
    depends_on:
    - postgres
    volumes:
    - ./etc:/hockeypuck/etc
    - ./keydump:/hockeypuck/import/dump
    - hkp_data:/hockeypuck/data
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  postgres:
    ports:
    - "5432:5432"
    image: postgres
    restart: always
    environment:
    - POSTGRES_USER=docker
    - POSTGRES_PASSWORD=docker
    - POSTGRES_DB=hkp
    volumes:
    - pg_data:/var/lib/postgresql/data

  nginx:
    image: nginx:1.17.3
    ports:
    - "80:80"
    - "443:443"
    restart: always
    depends_on:
    - hockeypuck
    volumes:
    - ./nginx/conf.d:/etc/nginx/conf.d
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    logging:
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  hkp_data: {}
  pg_data: {}
